let Var1 = document.createElement('head')
let Var2 = document.createElement('meta')
Var2.charset="utf-8"
let Var3 = document.createElement('title')
let Var4 = document.createElement('meta')
Var4.name="viewport"
Var4.content="width=device-width,initial-scale=1.0"
let Var5 = document.createElement('link')
Var5.rel="stylesheet"
Var5.href="./style.css"
Var5.type="text/css"
Var5.media="screen"
let Var6 = document.createElement('link')
Var6.rel="stylesheet"
Var6.id="wp-block-library-css"
Var6.href="./styleblocks.css"
Var6.blocks.csstype=text/css/""
Var6.media="all"
let Var7 = document.createElement('link')
Var7.rel="stylesheet"
Var7.href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
let Var8 = document.createElement('script')
Var8.src="./index.js"
